version: "3"

services:
  mockservr:
    command: npm run start-dev
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "8085:80"
      - "8045:4580"

  webpack:
    image: node:11-alpine
    environment:
      - "API_URL=http://localhost:8045/api/"
    working_dir: /usr/src/app/gui
    command: yarn start
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "8086:8086"
